### PR TITLE
Add support for connecting to redis server over SSL

### PR DESCRIPTION
**Pull request by Ashish-Bansal**
#### Description

Fixes https://github.com/gamenet/redis-memory-analyzer/issues/49

Intention of this PR is to provide very basic support for connecting to redis server over SSL. It doesn't perform any kind of cert verification which means connection to redis server won't be secure.

### CODE REVIEW

**Comment by Ashish-Bansal** [comment]
As for those failing tests, let me know if this project is active - I can look into more details then.

**Comment by misterion** [comment]
@Ashish-Bansal yes please. Could you check why it`s failed with Python 3.4.х ?

**Comment by Ashish-Bansal** [comment]
@misterion Python 3.4.x reached end of life. redis-py dropped support for the same. That's the reason tests are failing. Do we want to retain its support ?

**Comment by misterion** [comment]
@Ashish-Bansal i`m not deep involved in python, sorry. You are right, may i ask you to remove 3.4 from .travis.yml in this request?

**Pull request merged**
